trailingComma: "none"
printWidth: 500
tabWidth: 4
semi: false
singleQuote: false
arrowParens: "avoid"

plugins:
    - "prettier-plugin-svelte"
overrides:
    - files: "*.svelte"
      options:
          parser: "svelte"
